server:
  port: 8080

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
    operationsSorter: "method"
  api-docs:
    path: "/api-docs"

spring:
  application:
    name: pix-manager
  jackson:
    serialization:
      write_dates_as_timestamps: false
  data:
    jdbc:
      repositories:
        enabled: false
  jpa:
    properties:
      hibernate:
        format_sql: true
    show_sql: false
  datasource:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    url: jdbc:mysql://localhost:3306/pixdatabase?allowPublicKeyRetrieval=true&useSSL=false
    username: pixuser
    password: 20220125
    hikari:
      schema: pix_manager

locale:
  i18n:
    language: pt
    country: BR

eureka:
  client:
    enabled: false
    defaultZone: ${EUREKA_URI:http://localhost:8761/pixmanager}
    instance:
      prefer-ip-address: true